#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE customerdb;
    CREATE DATABASE loanapplicationdb;
    CREATE DATABASE civildb;
    GRANT ALL PRIVILEGES ON DATABASE customerdb TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE loanapplicationdb TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE civildb TO $POSTGRES_USER;
EOSQL
